### ISSUE TITLE
Unable to run the script files due to missing paket files

### ISSUE THREAD

**Issue by Zaid-Ajaj** [halcwb/GenOrder#1]
Script files within `./src/Informedica.GenOrder.Lib/Scripts` cannot run because they seem to have this reference:
```fsharp
#load "../../../.paket/load/netstandard2.1/main.group.fsx"
```
Which I can't find anywhere in the repository. Maybe this requires an older version of paket? I am using the paket cli tool (latest)

**Comment by halcwb** [comment]
Hello Zaid. Sorry, didn't read your issue until know. The loading script you mention can be generated by paket: `.paket/paket.exe generate-load-scripts`. This will generate the necessary load scripts to reference dependencies according to installed frameworks. This is a very useful paket utility I use all the time.

**Comment by Zaid-Ajaj** [comment]
I see, so I need to run the command `.paket/paket.exe generate-load-scripts` to get it to work. I will give that a try. The problem is that I am using latest paket build which is now distributed as a dotnet CLI tool available on the system so I didn't think I would need to run the packaged paket.exe available in the repository. The probably needs an update to use latest paket as a [local dotnet CLI tool](https://andrewlock.net/new-in-net-core-3-local-tools/) instead of paket.exe which requires `mono` on linux to run.

**Comment by halcwb** [comment]
If you mean `dotnet build`? This will just build your project (with use of paket) but will not generate the load scripts. Of course you don't need to generate load scripts just for the build, only to get the dependencies referenced in your script files. I will get this project a lot cleaner for the master branch.
